/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2014-04-29 19:30:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AllFiles.JSP.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.dao.UserDAO;
import com.dao.DAO;
import java.sql.*;

public final class newuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 
public int convert(String str) 
{ 
	int conv=0; 
	if(str==null) 
	{ 
		str="0"; 
	} 
	else if((str.trim()).equals("null")) 
	{ 
		str="0"; 
	} 
	else if(str.equals("")) 
	{ 
		str="0"; 
	} 
	try
	{ 
		conv=Integer.parseInt(str); 
	} 
	catch(Exception e) 
	{ 
	} 
	return conv; 
	
} 

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Admin Login Page</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/AllFiles/CSS/style.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/AllFiles/CSS/message.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath() );
      out.write("/AllFiles/JS/style.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- STYLE -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#login {\r\n");
      out.write("\tmargin: 5em auto;\r\n");
      out.write("\tbackground: #8FBC8F;\r\n");
      out.write("\tborder: 10px solid #F5F5DC;\r\n");
      out.write("\twidth: 450px;\r\n");
      out.write("\theight: 520px;\r\n");
      out.write("\talign: center;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 300px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("background-color: #8FBC8F; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login a,#login a:visited {\r\n");
      out.write("\tcolor: #0283b2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login a:hover {\r\n");
      out.write("\tcolor: #111;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login h1 {\r\n");
      out.write("\tcolor: #5BACC4;\r\n");
      out.write("\ttext-shadow: #007dab 0 2px 0;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tpadding: 18px 23px;\r\n");
      out.write("\tmargin: 0 0 1.5em 0;\r\n");
      out.write("\tborder-bottom: 1px solid #007dab;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login .field {\r\n");
      out.write("\tborder: 5px solid #F5F5DC;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 1.5em;\r\n");
      out.write("\tpadding: 4px;\r\n");
      out.write("\t-moz-box-shadow: inset 0 0 5px #ccc;\r\n");
      out.write("\t-webkit-box-shadow: inset 0 0 5px #ccc;\r\n");
      out.write("\tbox-shadow: inset 0 0 50px #8FBC8F;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login div.submit label {\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login button {\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tpadding: 0 30px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\ttext-shadow: #007dab 0 1px 0;\r\n");
      out.write("\tbackground: #424242;\r\n");
      out.write("\t-moz-border-radius: 50px;\r\n");
      out.write("\t-webkit-border-radius: 50px;\r\n");
      out.write("\tborder-radius: 50px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction check()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.f1.username.value.length==0 && document.f1.password.value.length==0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.location.href = 'index.jsp?no=1';\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.f1.username.value.length==0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.location.href = 'index.jsp?no=2';\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.f1.password.value.length==0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\twindow.location.href = 'index.jsp?no=3';\r\n");
      out.write("\t\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int no=convert(request.getParameter("no"));
	if(no==1)
	{
		    

      out.write("\r\n");
      out.write("<div class=\"error\" id=\"message\"\r\n");
      out.write("\tstyle=\"position: absolute; top: 130px; left: 530px\">\r\n");
      out.write("\t<p>Enter Username and Password !</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

	}
	if(no==2)
	{

      out.write("\r\n");
      out.write("<div class=\"error\" id=\"message\"\r\n");
      out.write("\tstyle=\"position: absolute; top: 130px; left: 530px\">\r\n");
      out.write("\t<p>Please,Enter Your Username.!</p>\r\n");
      out.write("</div>\r\n");

	}
	if(no==3)
	{

      out.write("\r\n");
      out.write("<div class=\"error\" id=\"message\"\r\n");
      out.write("\tstyle=\"position: absolute; top: 130px; left: 530px\">\r\n");
      out.write("\t<p>Please,Enter Your Password.!</p>\r\n");
      out.write("</div>\r\n");

	}

      out.write('\r');
      out.write('\n');

	if(no==4)
	{

      out.write("\r\n");
      out.write("<div class=\"error\" id=\"message\"\r\n");
      out.write("\tstyle=\"position: absolute; top: 130px; left: 530px\">\r\n");
      out.write("\t<p>Sorry,Invalid Username/Password!</p>\r\n");
      out.write("</div>\r\n");

	}

      out.write('\r');
      out.write('\n');

	if(no==5)
	{

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"success\" id=\"message\"\r\n");
      out.write("\tstyle=\"position: absolute; top: 130px; left: 500px\">\r\n");
      out.write("\t<p id=\"message\">You have Logged out successfully...!</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body onload=\"startTimer()\">\r\n");
      out.write("\r\n");
      out.write("\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/Top.jpg\"\r\n");
      out.write("\t\twidth=\"1024\" style=\" position: absolute;top: -5px;\"></img>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"a2\" align=\"right\" style=\"position: absolute; top: 0px; left: 25px\">\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t<table id=\"login\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/NewUser\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"7\" align=\"center\"><font color=\"#000000\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-style: bold; font-family: monotype corsiva\" size=\"6\">User\r\n");
      out.write("\t\t\t\t\t\t\tRegistration</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" align=\"center\"><hr></hr></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td width=\"175px\">User Id</td>\r\n");
      out.write("\t\t\t\t<td width=\"75px\">:</td>\r\n");
      out.write("\t\t\t\t<td width=\"200px\"><input class=\"field\" type=\"text\" name=\"userid\"\r\n");
      out.write("\t\t\t\t\trequired=\"yes\" placeholder=\"Enter Your Id\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td>Password</td>\r\n");
      out.write("\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t<td><input class=\"field\" type=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\trequired=\"yes\" placeholder=\"Enter Your Password\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td>Name</td>\r\n");
      out.write("\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t<td><input class=\"field\" type=\"text\" name=\"name\"\r\n");
      out.write("\t\t\t\t\trequired=\"yes\"  placeholder=\"Enter Your Name\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr align=\"center\" >\r\n");
      out.write("\t\t\t\t<td>Domain</td>\r\n");
      out.write("\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t<td><select class=\"field\" name=\"domain\" required=\"yes\" >\r\n");
      out.write("\t\t\t\t<option value=\"\">Domain Code</option>\r\n");
      out.write("\t\t\t\t\t\t");


	String value;
	String name="";
 	Connection connection = null;
 	Statement statement = null;
 	ResultSet resultSet = null;
 	UserDAO userDAO=null;
	DAO dao=DAO.getInstance();
	connection=dao.connector();
	statement = connection.createStatement();
	resultSet = statement.executeQuery("select domain_code,domain_name from m_domain");
		while(resultSet.next())
		{
			value=resultSet.getString(1);
			name=resultSet.getString(2);
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(value);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(name);
      out.write("</option>\r\n");
      out.write("\t\t\t");
 
		
		}


	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td>SubDomain</td>\r\n");
      out.write("\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t<td><select class=\"field\" name=\"subdomain\" required=\"yes\">\r\n");
      out.write("\t\t\t\t<option value=\"\">Sub Domain Code</option>\r\n");
      out.write("\t\t\t\t\t\t");


	String sub_code;
 	String sd_name="";
 	UserDAO userDAO1=null;
	DAO dao1=DAO.getInstance();
	connection=dao.connector();
	statement = connection.createStatement();
	resultSet = statement.executeQuery("select sdomain_code,sdomain_name from m_subdomain");
		while(resultSet.next())
		{
			sub_code=resultSet.getString(1);
			sd_name=resultSet.getString(2);
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<option value=\"");
      out.print(sub_code);
      out.write("\" style=\"width: 300px;\">");
      out.print(sd_name);
      out.write("</option>\r\n");
      out.write("\t\t\t");
 
		
		}


	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td>UserEmail</td>\r\n");
      out.write("\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t<td><input class=\"field\" type=\"email\" name=\"email\" required=\"yes\" placeholder=\"Enter Your Email\" pattern=\"\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" align=\"center\"><input class=\"button\"\r\n");
      out.write("\t\t\t\t\ttype=\"submit\" value=\"Register\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"position: absolute; top: 200px; left: 50px\"></div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<iframe name=\"a\" width=\"0\" height=\"0\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
